<?php

namespace App\Trait;

use App\Models\Website;
use Filament\Actions\Action;
use Filament\Support\Colors\Color;

trait TemplatePreviewActionTrait
{
    protected function getHeaderActions(): array
    {
        return [
            $this->getPreviewActionButton()
        ];
    }

    protected function getFormActions(): array
    {
        return [
            ...parent::getFormActions(),
            $this->getPreviewActionButton()
        ]; // TODO: Change the autogenerated stub
    }

    public function getPreviewActionButton()
    {
        return Action::make('preview')
            ->color(Color::Orange)
            ->url(function (Website $record) {
                return route(
                    'website-theme-preview',
                    [
                        'website' => $record->uuid
                    ]
                );
            }, true);
    }
}
