<?php

namespace App\Trait;

use App\Filament\Resources\TemplateOneMediaPickerResource;
use App\Models\Website;
use Filament\Actions\Action;
use Filament\Support\Colors\Color;

trait TemplatePreviewActionTrait
{
    protected function getHeaderActions(): array
    {
        return [
            $this->getPreviewActionButton(),
            $this->getRedirectToMediaPickerAction()
        ];
    }

    protected function getFormActions(): array
    {
        return [
            ...parent::getFormActions(),
            $this->getPreviewActionButton(),
            $this->getRedirectToMediaPickerAction()
        ]; // TODO: Change the autogenerated stub
    }

    public function getPreviewActionButton()
    {
        return Action::make('preview')
            ->color(Color::Orange)
            ->url(function (Website $record) {
                return route(
                    'website-theme-preview',
                    [
                        'website' => $record->uuid
                    ]
                );
            }, true);
    }

    public function getRedirectToMediaPickerAction()
    {
        return Action::make('use_media_picker')
            ->color(Color::Emerald)
            ->disabled(function () {
                return \Route::getCurrentRoute()->getName() !== 'filament.admin.resources.template-ones.edit';
            })
            ->url(function (Website $record) {
                return TemplateOneMediaPickerResource::getUrl('edit', ['record' => $record->id]);
            });
    }
}
